name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Debug: List root directory contents' # NEW DEBUG STEP
        run: ls -la

      - name: 'Debug: List cypress-realworld-app directory contents' # NEW DEBUG STEP
        run: ls -la ./cypress-realworld-app

      - name: Install test project dependencies
        run: npm ci # Assuming your main project uses npm, or adjust to yarn if needed

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          yarn install --frozen-lockfile # Use frozen-lockfile for deterministic installs

      - name: 'Debug: Print package.json content' # Enclosed in single quotes
        working-directory: ./cypress-realworld-app
        run: cat package.json

      - name: 'Debug: List Yarn Scripts' # Enclosed in single quotes
        working-directory: ./cypress-realworld-app
        run: yarn run

      - name: Start Real World App (on localhost:3000)
        working-directory: ./cypress-realworld-app
        run: |
          set -eux
          (yarn start:api:watch &) # Wrapped in subshell to handle '&' for YAML parser
          (yarn start:react &)    # Wrapped in subshell to handle '&' for YAML parser
          npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
