name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install test project dependencies
        run: npm ci # Assuming your main project uses npm, or adjust to yarn if needed

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          yarn install --frozen-lockfile # Use frozen-lockfile for deterministic installs

      - name: { Debug: "Print package.json content" }
        working-directory: ./cypress-realworld-app
        run: cat package.json

      - name: { Debug: "List Yarn Scripts" }
        working-directory: ./cypress-realworld-app
        run: yarn run

      - name: Start Real World App (on localhost:3000)
        working-directory: ./cypress-realworld-app
        run: |
          set -eux # -e: exit on error, -u: unset variables as error, -x: print commands and arguments as they are executed.
          # The 'yarn dev' command was failing, so we're directly running its constituent parts.
          # The 'dev' script in package.json runs:
          # "concurrently yarn:start:react yarn:start:api:watch"
          # We will run these two commands in the background.
          yarn start:api:watch & # Starts the API server
          yarn start:react &    # Starts the React frontend (likely on localhost:3000)
          npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots