name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install test project dependencies
        run: npm ci # Assuming your main project uses npm, or adjust to yarn if needed

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          # Use --ignore-scripts to prevent the 'postinstall' script (which includes husky) from failing.
          yarn install --frozen-lockfile --ignore-scripts # Keep --ignore-scripts

      - name: Apply Patches for Real World App # NEW STEP: Explicitly run patch-package
        working-directory: ./cypress-realworld-app
        run: npx patch-package || true # Use npx to ensure patch-package is found.
        # `|| true` makes this step not fail the workflow if no patches are applied or if it's a non-critical error.

      - name: 'Debug: Print package.json content'
        working-directory: ./cypress-realworld-app
        run: cat package.json

      - name: 'Debug: List Yarn Scripts'
        working-directory: ./cypress-realworld-app
        run: yarn run

      - name: Start Real World App (on localhost:3000)
        working-directory: ./cypress-realworld-app
        run: |
          set -eux
          (yarn start:api:watch &) # Wrapped in subshell to handle '&' for YAML parser
          (yarn start:react &)    # Wrapped in subshell to handle '&' for YAML parser
          npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
