name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install test project dependencies
        run: npm ci # Assuming your main project uses npm, or adjust to yarn if needed

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app # This step correctly targets the sub-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          # Use --ignore-scripts to prevent the 'postinstall' script (which includes husky) from failing.
          yarn install --frozen-lockfile --ignore-scripts # Keep --ignore-scripts

      - name: Apply Patches for Real World App
        working-directory: ./cypress-realworld-app # This step correctly targets the sub-app
        run: npx patch-package || true # Use npx to ensure patch-package is found.

      - name: Start Servers and Run Cypress Tests # Renamed and modified step
        # This step runs from the root of the repository, where Cypress is configured.
        run: |
          # Use start-server-and-test to reliably start both servers and wait for them
          # before executing Cypress tests.
          # We explicitly 'cd' into the sub-app directory for the server commands.
          npx start-server-and-test \
            "cd ./cypress-realworld-app && yarn start:api" http://localhost:3001 \
            "cd ./cypress-realworld-app && yarn start:react" http://localhost:3000 \
            "npx cypress run" # This command will run from the root, finding Cypress files.

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots # These paths are relative to the root, which is now correct.
