name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install test project dependencies
        run: npm ci # Assuming your main project uses npm, or adjust to yarn if needed

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          # Use --ignore-scripts to prevent the 'postinstall' script (which includes husky) from failing.
          yarn install --frozen-lockfile --ignore-scripts # Keep --ignore-scripts

      - name: Apply Patches for Real World App
        working-directory: ./cypress-realworld-app
        run: npx patch-package || true # Use npx to ensure patch-package is found.

      - name: Start Real World App (on localhost:3000)
        working-directory: ./cypress-realworld-app
        run: |
          set -eux
          # Start API and React in the background using nohup to ensure they are fully detached.
          # Redirect output to log files to prevent stdout/stderr from blocking.
          nohup yarn start:api > api.log 2>&1 &    # Starts the API server without nodemon
          nohup yarn start:react > react.log 2>&1 & # Starts the React frontend (Vite)
          npx wait-on http://localhost:3000         # Wait for the React app to be ready (moved to last)

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
