name: Run Cypress Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install test project dependencies
        run: npm ci

      - name: Install Cypress Reporter Dependencies
        run: npm install mochawesome mochawesome-report-generator

      - name: Install Real World App dependencies
        working-directory: ./cypress-realworld-app
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          yarn cache clean # Clear yarn cache to ensure fresh install
          # Use --ignore-scripts to prevent the 'postinstall' script (which includes husky) from failing.
          yarn install --frozen-lockfile --ignore-scripts # Keep --ignore-scripts

      - name: Apply Patches for Real World App
        working-directory: ./cypress-realworld-app
        run: npx patch-package || true

      - name: Start Servers and Run Cypress Tests
        run: |
          npx start-server-and-test \
            "cd ./cypress-realworld-app && yarn start:api" http://localhost:3001 \
            "cd ./cypress-realworld-app && yarn start:react" http://localhost:3000 \
            "npx cypress run" # This command will run from the root, finding Cypress files.

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            mochawesome-report 
